### ISSUE TITLE
crash when chose movie that not has been fully loaded

### ISSUE THREAD

**Issue by muhammadarif1** [bapspatil/FlickOff#1]
#### EXPECTED BEHAVIOR 
 when a user chooses to view a movie that has not been fully loaded the user should be able to get into the movie while waiting for the movie to be fully loaded

#### ACTUAL BEHAVIOR
when a user enters a movie whose thumbnail has not been loaded the app crashes and stops working

#### HOW TO REPRODUCE 
- install flick off app from github release
- After successfully installed launch its app
- find whatever movie you want
- select movies with thumbnails that have not been fully loaded
- and see if the app will crash 
- if the bug does not appear choose another unfilled movie whose thumbnail has not been loaded yet

browser : flick off v1.3.2
device: android 6.0 xiaomi 

#### BUG RECORDING 
https://youtu.be/_hmXzs34PW0

#### LOGCAT FILE 
```FATAL EXCEPTION: main
Process: bapspatil.flickoff, PID: 19588
java.lang.RuntimeException: Unable to start activity ComponentInfo{bapspatil.flickoff/bapspatil.flickoff.ui.DetailsActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method c.a.a.b.b, parameter posterPath
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2367)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
	at android.app.ActivityThread.access$800(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5376)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method c.a.a.b.b, parameter posterPath
	at bapspatil.flickoff.b.c.<init>(Unknown Source)
	at bapspatil.flickoff.b.c$a.createFromParcel(Unknown Source)
	at android.os.Parcel.readParcelable(Parcel.java:2252)
	at android.os.Parcel.readValue(Parcel.java:2152)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
	at android.os.BaseBundle.containsKey(BaseBundle.java:269)
	at android.content.Intent.hasExtra(Intent.java:4978)
	at bapspatil.flickoff.ui.DetailsActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6012)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
	... 10 more```

**Comment by bapspatil** [comment]
@muhammadarif1 Thank you for this detailed bug report! 
It'll be fixed in version 1.3.3.
